### PR TITLE
Fix normalize calls recursion with other plugin

### LINKED ISSUE #16: Causes infinite normalize calls in steal@1.0.0.rc

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #16

cc: @matthewp

### CODE REVIEW

File: test/steal-noop.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+exports.translate = function(load) {
```
Comment (matthewp) [inline test/steal-noop.js]: Since you're just using normalize() I don't think this file is even needed. It's not loaded until `locate` occurs, which doesn't in your test.

File: package.json [hunk 2]
```diff
@@ -28,11 +28,10 @@
     "url": "https://github.com/stealjs/conditional/issues"
   },
   "homepage": "https://github.com/stealjs/conditional",
-  "dependencies": {
-    "steal": "^0.15.0"
-  },
   "devDependencies": {
     "jshint": "^2.9.1",
+    "steal": "^1.0.0-rc.10",
+    "steal-css": "^1.0.0-rc.0",
```
Comment (matthewp) [inline package.json:34]: Looks like you're not using steal-css, right?

**Review by matthewp — CHANGES_REQUESTED** [review]

File: package.json (hunk 2 above)
Comment (m-mujica) [reply package.json:34]: I had to install it because of `steal-qunit`, it loads qunit's css

File: test/steal-noop.js (hunk 1 above)
Comment (m-mujica) [reply test/steal-noop.js]: let me try removing it

**Review by matthewp — APPROVED** [review]
